# Generated by Django 3.1.4 on 2021-02-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer1',
            },
        ),
    ]
