# Generated by Django 3.1.4 on 2021-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210203_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('message', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
